### PR TITLE
add formatToParts

### LINKED ISSUE #11: formatToParts
Would you accept a PR that adds a similar TZ-aware wrapper for [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts)?

### PR DESCRIPTION
**Pull request by icambron**
Implementation of `formatToParts`, closes #11

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by icambron** [comment]
I'm not sure how to make the checker recheck my CLA status, but anyway, I signed it.

**Comment by markandey** [comment]
@icambron great. Thanks . Please accept the CLA and this is good to merge.

**Comment by markandey** [comment]
👍

**Comment by icambron** [comment]
@markandey I accepted the CLA

**Pull request merged**
